// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGU_FCDdAj-gK7CYXDRPePaYL81kfK1Z8',
    appId: '1:133004211865:web:7e1c5fcfd21b56e5cbea08',
    messagingSenderId: '133004211865',
    projectId: 'to-do-riverpod',
    authDomain: 'to-do-riverpod.firebaseapp.com',
    databaseURL: 'https://to-do-riverpod-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-riverpod.appspot.com',
    measurementId: 'G-7ZW77VFDMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpnlaL1CIp4kHadaDsDG-aZcC7mYUgwQU',
    appId: '1:133004211865:android:fe08e1ea87a00853cbea08',
    messagingSenderId: '133004211865',
    projectId: 'to-do-riverpod',
    databaseURL: 'https://to-do-riverpod-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIaXCRMjYpxu_0jzyw9DlfJUx5HzgVUwA',
    appId: '1:133004211865:ios:27bbe5f52af1cd52cbea08',
    messagingSenderId: '133004211865',
    projectId: 'to-do-riverpod',
    databaseURL: 'https://to-do-riverpod-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-riverpod.appspot.com',
    androidClientId: '133004211865-9ja0mnsdu71lkg1mkosl4afddd2fmf4q.apps.googleusercontent.com',
    iosClientId: '133004211865-jqbfi88ch3ap4ft9agqn1r5hfeho9d4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIaXCRMjYpxu_0jzyw9DlfJUx5HzgVUwA',
    appId: '1:133004211865:ios:5dfbb8aa1e6a4e7fcbea08',
    messagingSenderId: '133004211865',
    projectId: 'to-do-riverpod',
    databaseURL: 'https://to-do-riverpod-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-riverpod.appspot.com',
    androidClientId: '133004211865-9ja0mnsdu71lkg1mkosl4afddd2fmf4q.apps.googleusercontent.com',
    iosClientId: '133004211865-h7eiad1geiu5nnr0ocqn678etv07vlt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoRiverpod.RunnerTests',
  );
}
